version: "3.8"
services:
  users:
    build:
      context: .
      dockerfile: dockerfiles/users.dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./env/users.env
  auth:
    build:
      context: .
      dockerfile: dockerfiles/auth.dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./env/auth.env
  tasks:
    build:
      context: .
      dockerfile: dockerfiles/tasks.dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./env/tasks.env
    volumes:
      - tasks:/app/tasks:rw

  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./env/frontend.env

volumes:
  tasks:
