apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasks-pvc
spec:
  storageClassName: standard
  volumeName: tasks-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
